#! /bin/sh

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor DisplayPort-0 -d I II III IV V
bspc monitor DisplayPort-1 -d VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          12

bspc config presel_feedback_color "#ffffff"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config top_padding 25

# border colors
bspc config focused_border_color "#53888b"
bspc config normal_border_color "#264c4f"


# Autostart

# sxhkd
sxhkd &

# polybar
~/.config/polybar/launch.sh &

# compositor and wallpaper
picom --config ~/.config/picom/picom.conf &
feh --bg-max --randomize ~/.config/wallpapers/*
